apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nri-cdi-device-injector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nri-plugin.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - watch
