apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nri-cdi-device-injector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nri-plugin.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nri-cdi-device-injector
subjects:
- kind: ServiceAccount
  name: nri-cdi-device-injector
  namespace: {{ .Release.Namespace }}
